import { Article } from '../articles/Article';
import { Tip } from '../tips/Tip';

interface ValidationResult {
  isValid: boolean;
  errors?: string[];
  score?: number;
}

export class ContentValidationService {
  private readonly MIN_WORD_COUNT = 800;
  private readonly MAX_WORD_COUNT = 2000;
  private readonly MIN_READABILITY_SCORE = 7.0;
  private readonly MAX_READABILITY_SCORE = 10.0;

  async validateArticle(article: Article): Promise<ValidationResult> {
    const errors: string[] = [];
    
    // Word count validation
    if (article.word_count < this.MIN_WORD_COUNT) {
      errors.push(`Article too short: ${article.word_count} words (minimum ${this.MIN_WORD_COUNT})`);
    }
    
    if (article.word_count > this.MAX_WORD_COUNT) {
      errors.push(`Article too long: ${article.word_count} words (maximum ${this.MAX_WORD_COUNT})`);
    }
    
    // Readability validation
    if (article.readability_score < this.MIN_READABILITY_SCORE) {
      errors.push(`Readability score too low: ${article.readability_score} (minimum ${this.MIN_READABILITY_SCORE})`);
    }
    
    if (article.readability_score > this.MAX_READABILITY_SCORE) {
      errors.push(`Readability score too high: ${article.readability_score} (maximum ${this.MAX_READABILITY_SCORE})`);
    }
    
    // Content quality checks
    const contentAnalysis = this.analyzeContentQuality(article.content);
    if (contentAnalysis.errors.length > 0) {
      errors.push(...contentAnalysis.errors);
    }
    
    // SEO validation
    const seoAnalysis = this.validateSEO(article);
    if (seoAnalysis.errors.length > 0) {
      errors.push(...seoAnalysis.errors);
    }
    
    // Structure validation
    const structureAnalysis = this.validateStructure(article.content);
    if (structureAnalysis.errors.length > 0) {
      errors.push(...structureAnalysis.errors);
    }
    
    const isValid = errors.length === 0;
    const score = this.calculateQualityScore(article, errors);
    
    return {
      isValid,
      errors: isValid ? undefined : errors,
      score
    };
  }

  async validateTip(tip: Tip): Promise<ValidationResult> {
    const errors: string[] = [];
    
    // Tip-specific validation
    if (tip.word_count < 100) {
      errors.push(`Tip too short: ${tip.word_count} words (minimum 100)`);
    }
    
    if (tip.word_count > 500) {
      errors.push(`Tip too long: ${tip.word_count} words (maximum 500)`);
    }
    
    // Content quality check
    if (!this.isActionable(tip.content)) {
      errors.push('Tip content is not actionable enough');
    }
    
    const isValid = errors.length === 0;
    
    return {
      isValid,
      errors: isValid ? undefined : errors
    };
  }

  private analyzeContentQuality(content: string): { errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    // Check for AI detection patterns (basic)
    const aiPatterns = [
      /as an ai language model/i,
      /as a large language model/i,
      /i am an ai/i,
      /generated by ai/i
    ];
    
    aiPatterns.forEach(pattern => {
      if (pattern.test(content)) {
        errors.push('Content contains AI disclosure patterns');
      }
    });
    
    // Check for repetition
    const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 0);
    const uniqueSentences = new Set(sentences.map(s => s.trim().toLowerCase()));
    
    if (uniqueSentences.size / sentences.length < 0.7) {
      warnings.push('High sentence repetition detected');
    }
    
    // Check paragraph structure
    const paragraphs = content.split('\n\n').filter(p => p.trim().length > 0);
    const shortParagraphs = paragraphs.filter(p => p.split(/\s+/).length < 3);
    
    if (shortParagraphs.length > paragraphs.length * 0.3) {
      warnings.push('Too many short paragraphs');
    }
    
    return { errors, warnings };
  }

  private validateSEO(article: Article): { errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    // Title length check
    if (article.title.length < 40) {
      warnings.push('Title might be too short for SEO (minimum 40 characters recommended)');
    }
    
    if (article.title.length > 70) {
      warnings.push('Title might be too long for SEO (maximum 70 characters recommended)');
    }
    
    // Meta description length
    if (article.meta_description && article.meta_description.length < 120) {
      warnings.push('Meta description might be too short for SEO (minimum 120 characters recommended)');
    }
    
    if (article.meta_description && article.meta_description.length > 160) {
      warnings.push('Meta description might be too long for SEO (maximum 160 characters recommended)');
    }
    
    // Keyword density (basic check)
    const content = article.content.toLowerCase();
    const titleWords = article.title.toLowerCase().split(/\s+/);
    
    titleWords.forEach(word => {
      if (word.length > 3) { // Only check meaningful words
        const regex = new RegExp(`\\b${word}\\b`, 'g');
        const matches = content.match(regex);
        const density = matches ? matches.length / (article.word_count / 100) : 0;
        
        if (density < 0.5) {
          warnings.push(`Keyword "${word}" appears too infrequently (density: ${density.toFixed(2)}%)`);
        }
        
        if (density > 3.0) {
          warnings.push(`Keyword "${word}" might be over-optimized (density: ${density.toFixed(2)}%)`);
        }
      }
    });
    
    return { errors, warnings };
  }

  private validateStructure(content: string): { errors: string[]; warnings: string[] } {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    // Check for headings
    const headingCount = (content.match(/^#{1,6}\s+.+$/gm) || []).length;
    
    if (headingCount < 3) {
      warnings.push('Low heading count - consider adding more section headers');
    }
    
    // Check for lists
    const listCount = (content.match(/^[*-]\s+.+$/gm) || []).length;
    
    if (listCount < 2) {
      warnings.push('Consider adding more bullet points or numbered lists for readability');
    }
    
    // Check paragraph length variety
    const paragraphs = content.split('\n\n').filter(p => p.trim().length > 0);
    const wordCounts = paragraphs.map(p => p.split(/\s+/).length);
    
    const avgWords = wordCounts.reduce((sum, count) => sum + count, 0) / wordCounts.length;
    const variedParagraphs = wordCounts.filter(count => 
      count < avgWords * 0.5 || count > avgWords * 1.5
    ).length;
    
    if (variedParagraphs / paragraphs.length < 0.2) {
      warnings.push('Paragraph lengths lack variety - consider mixing short and long paragraphs');
    }
    
    return { errors, warnings };
  }

  private isActionable(content: string): boolean {
    // Check if content contains actionable language
    const actionablePatterns = [
      /how to/i,
      /step by step/i,
      /try this/i,
      /you should/i,
      /recommend/i,
      /suggest/i,
      /tip:/i,
      /advice/i
    ];
    
    return actionablePatterns.some(pattern => pattern.test(content));
  }

  private calculateQualityScore(article: Article, errors: string[]): number {
    let score = 100;
    
    // Deduct points for errors
    score -= errors.length * 10;
    
    // Word count optimization
    const wordCountDeviation = Math.abs(article.word_count - 1200) / 1200;
    score -= wordCountDeviation * 20;
    
    // Readability optimization
    const readabilityDeviation = Math.abs(article.readability_score - 8.5) / 8.5;
    score -= readabilityDeviation * 15;
    
    // Ensure score is within bounds
    return Math.max(0, Math.min(100, Math.round(score)));
  }

  // Bulk validation methods
  async validateMultipleArticles(articles: Article[]): Promise<Map<string, ValidationResult>> {
    const results = new Map<string, ValidationResult>();
    
    for (const article of articles) {
      const result = await this.validateArticle(article);
      results.set(article.id, result);
    }
    
    return results;
  }

  async validateMultipleTips(tips: Tip[]): Promise<Map<string, ValidationResult>> {
    const results = new Map<string, ValidationResult>();
    
    for (const tip of tips) {
      const result = await this.validateTip(tip);
      results.set(tip.id, result);
    }
    
    return results;
  }

  // Quick validation for UI integration
  async quickValidate(content: string, type: 'article' | 'tip'): Promise<ValidationResult> {
    const tempArticle = Article.build({
      title: 'Temporary',
      slug: 'temporary-validation',
      content: content,
      word_count: this.countWords(content),
      readability_score: this.calculateReadability(content),
      meta_description: '',
      category: 'General',
      tags: [],
      geo_focus: 'Global',
      type: 'Guide',
      status: 'draft',
      ai_generated: true,
      validation_passed: false
    });
    
    return await this.validateArticle(tempArticle);
  }

  private countWords(text: string): number {
    return text.split(/\s+/).filter(word => word.length > 0).length;
  }

  private calculateReadability(text: string): number {
    const words = text.split(/\s+/).length;
    const sentences = text.split(/[.!?]+/).length;
    
    if (words === 0 || sentences === 0) return 8.0;
    
    const averageWordsPerSentence = words / sentences;
    return Math.max(6, Math.min(10, 11 - (averageWordsPerSentence * 0.1)));
  }
}