// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/social-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/social-keys">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/social-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/advertise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/advertise">> = Specific
  const handler = {} as typeof import("../../src/app/advertise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ama/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ama/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/ama/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ama/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ama">> = Specific
  const handler = {} as typeof import("../../src/app/ama/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/auth-code-error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/auth-code-error">> = Specific
  const handler = {} as typeof import("../../src/app/auth/auth-code-error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/[category]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/[category]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/education/[category]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/education/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/exam-prep/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/exam-prep/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/education/exam-prep/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/exam-prep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/exam-prep">> = Specific
  const handler = {} as typeof import("../../src/app/education/exam-prep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education">> = Specific
  const handler = {} as typeof import("../../src/app/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/study-guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/study-guides/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/education/study-guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/study-guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/study-guides">> = Specific
  const handler = {} as typeof import("../../src/app/education/study-guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/study-techniques/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/study-techniques/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/education/study-techniques/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/education/study-techniques/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/education/study-techniques">> = Specific
  const handler = {} as typeof import("../../src/app/education/study-techniques/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/howto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides/howto">> = Specific
  const handler = {} as typeof import("../../src/app/guides/howto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guides">> = Specific
  const handler = {} as typeof import("../../src/app/guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/homepage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/homepage">> = Specific
  const handler = {} as typeof import("../../src/app/homepage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/howto/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/howto/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/howto/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/howto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/howto">> = Specific
  const handler = {} as typeof import("../../src/app/howto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-market/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-market/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/job-market/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-market/benefits-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-market/benefits-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/job-market/benefits-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-market/city-comparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-market/city-comparison">> = Specific
  const handler = {} as typeof import("../../src/app/job-market/city-comparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-market">> = Specific
  const handler = {} as typeof import("../../src/app/job-market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-market/salary-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-market/salary-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/job-market/salary-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lifestyle/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lifestyle/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/lifestyle/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lifestyle/nigerian-culture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lifestyle/nigerian-culture">> = Specific
  const handler = {} as typeof import("../../src/app/lifestyle/nigerian-culture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lifestyle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lifestyle">> = Specific
  const handler = {} as typeof import("../../src/app/lifestyle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/attractions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/attractions">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/attractions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/business-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/business-services">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/business-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/cafes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/cafes">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/cafes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/concerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/concerts">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/concerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/cost-of-living/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/cost-of-living">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/cost-of-living/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/events-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/events-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/events-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/family-events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/family-events">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/family-events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/festivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/festivals">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/festivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/food-delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/food-delivery">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/food-delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/freelancers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/freelancers">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/freelancers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/home-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/home-services">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/home-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/housing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/housing">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/housing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/itineraries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/itineraries">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/itineraries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/local-culture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/local-culture">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/local-culture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/lounges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/lounges">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/lounges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/neighborhoods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/neighborhoods">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/neighborhoods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/nigerian-cities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/nigerian-cities">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/nigerian-cities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/nightlife/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/nightlife">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/nightlife/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/places-to-visit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/places-to-visit">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/places-to-visit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/professionals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/professionals">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/professionals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/restaurants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/restaurants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/street-food/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/street-food">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/street-food/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/tech-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/tech-services">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/tech-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/local-resources/transportation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-resources/transportation">> = Specific
  const handler = {} as typeof import("../../src/app/local-resources/transportation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nigerian-cities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nigerian-cities">> = Specific
  const handler = {} as typeof import("../../src/app/nigerian-cities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nigerian-fintech/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nigerian-fintech/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/nigerian-fintech/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nigerian-fintech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nigerian-fintech">> = Specific
  const handler = {} as typeof import("../../src/app/nigerian-fintech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/press/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/press">> = Specific
  const handler = {} as typeof import("../../src/app/press/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qa">> = Specific
  const handler = {} as typeof import("../../src/app/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/accessories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/accessories/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/accessories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/accessories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/accessories">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/accessories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/alternatives/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/alternatives/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/alternatives/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/alternatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/alternatives">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/alternatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/business-books/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/business-books/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/business-books/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/business-books/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/business-books">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/business-books/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/business-tools/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/business-tools/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/business-tools/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/business-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/business-tools">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/business-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/buying-guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/buying-guides/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/buying-guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/buying-guides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/buying-guides">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/buying-guides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/cafes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/cafes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/cafes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/cafes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/cafes">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/cafes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/course-platforms/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/course-platforms/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/course-platforms/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/course-platforms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/course-platforms">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/course-platforms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/digital-platforms/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/digital-platforms/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/digital-platforms/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/digital-platforms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/digital-platforms">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/digital-platforms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/educational-books/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/educational-books/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/educational-books/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/educational-books/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/educational-books">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/educational-books/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/finance-apps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/finance-apps/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/finance-apps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/finance-apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/finance-apps">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/finance-apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/free-vs-paid/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/free-vs-paid/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/free-vs-paid/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/free-vs-paid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/free-vs-paid">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/free-vs-paid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/gadgets/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/gadgets/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/gadgets/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/gadgets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/gadgets">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/gadgets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/hotels/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/hotels/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/hotels/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/hotels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/hotels">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/hotels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/laptops/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/laptops/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/laptops/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/laptops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/laptops">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/laptops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/learning-apps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/learning-apps/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/learning-apps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/learning-apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/learning-apps">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/learning-apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/local-vendors/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/local-vendors/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/local-vendors/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/local-vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/local-vendors">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/local-vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/nigerian-fintech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/nigerian-fintech">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/nigerian-fintech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/online-services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/online-services/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/online-services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/online-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/online-services">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/online-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/productivity-apps/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/productivity-apps/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/productivity-apps/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/productivity-apps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/productivity-apps">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/productivity-apps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/restaurants/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/restaurants/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/restaurants/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/restaurants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/restaurants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/saas/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/saas/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/saas/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/saas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/saas">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/saas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/self-development/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/self-development/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/self-development/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/self-development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/self-development">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/self-development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/service-providers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/service-providers/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/service-providers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/service-providers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/service-providers">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/service-providers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/smartphones/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/smartphones/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/smartphones/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/smartphones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/smartphones">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/smartphones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/subscriptions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/subscriptions/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/subscriptions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/tablets/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/tablets/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/tablets/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/tablets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/tablets">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/tablets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/tech-books/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/tech-books/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/tech-books/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/tech-books/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews/tech-books">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/tech-books/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/technology/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/technology/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/technology/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/technology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/technology">> = Specific
  const handler = {} as typeof import("../../src/app/technology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tips">> = Specific
  const handler = {} as typeof import("../../src/app/tips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/topics/education/[category]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/topics/education/[category]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/topics/education/[category]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/topics/education/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/topics/education/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/topics/education/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/topics/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/topics/education">> = Specific
  const handler = {} as typeof import("../../src/app/topics/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/topics/technology/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/topics/technology/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/topics/technology/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/social-keys/[platform]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social-keys/[platform]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/social-keys/[platform]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/social-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/social-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-publishing/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-publishing/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-publishing/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ama/answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ama/answers">> = Specific
  const handler = {} as typeof import("../../src/app/api/ama/answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ama/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ama/questions">> = Specific
  const handler = {} as typeof import("../../src/app/api/ama/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ama/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ama/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/ama/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/[articleId]/reaction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[articleId]/reaction">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/[articleId]/reaction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/[articleId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/[articleId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/supabase">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/image-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-proxy">> = Specific
  const handler = {} as typeof import("../../src/app/api/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa/answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa/answers">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa/answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa/questions">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qa/upvotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qa/upvotes">> = Specific
  const handler = {} as typeof import("../../src/app/api/qa/upvotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reading-lists/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-lists/items">> = Specific
  const handler = {} as typeof import("../../src/app/api/reading-lists/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reading-lists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-lists">> = Specific
  const handler = {} as typeof import("../../src/app/api/reading-lists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reading-progress/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-progress/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/reading-progress/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reading-progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading-progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/reading-progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rss/[category]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rss/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/api/rss/[category]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/rss/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rss">> = Specific
  const handler = {} as typeof import("../../src/app/api/rss/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/social-shares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social-shares">> = Specific
  const handler = {} as typeof import("../../src/app/api/social-shares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
